### ISSUE TITLE
abi: add functions to encode/decode non-standard types like `uint128` etc.

### ISSUE THREAD

**Issue by mhw0** [mhw0/libethc#15]
`int eth_abi_mpint(struct eth_abi *abi, mpz_t *mpz)`

**Comment by DerXanRam** [comment]
> `int eth_abi_mpint(struct eth_abi *abi, mpz_t *mpz)` `int eth_rlp_mpint(struct eth_rlp *rlp, mpz_t *mpz)`

can u tell me when we will see this feature implmented ?

**Comment by mhw0** [comment]
As soon as I have free time. It's not hard to implement.

**Comment by DerXanRam** [comment]
ok bro. Thanks bro :pray:

**Comment by mhw0** [comment]
Hi  @DerXanRam. Can you pull the dev branch and test the `eth_abi_mpint`?

**Comment by DerXanRam** [comment]
> Hi  @DerXanRam. Can you pull the dev branch and test the `eth_abi_mpint`?

Ok..

I'm on it bro 👍

**Comment by mhw0** [comment]
Okay, could you open `ethc/abi.h` and put `#include <gmp.h>` before `#ifdef __cplusplus` and test?

**Comment by DerXanRam** [comment]
ok wait...

**Comment by mhw0** [comment]
You have to initialize `r1` and `r2` first (`mpz_init(r1)` etc).

**Comment by mhw0** [comment]
To print `mpz`s, do: `gmp_printf("%Zd\n", r1);`

**Comment by mhw0** [comment]
Try replacing `MP_INT` with `mpz_t`

> and is this the only way to print it...what about passing to char* ?

`gmp_printf` is compatible with `printf`, so, just works: `gmp_printf("%Zd %s\n", r1, "test");`

**Comment by DerXanRam** [comment]
and now this functions parameters are not compatible with `mpz_t`

```
eth_abi_mpint(&abi,&r1);
eth_abi_mpint(&abi,&r2);
```
the error is

[{
	"resource": "/home/biruk/Documents/eth/arb+tbot/uniswap.h",
	"owner": "C/C++: IntelliSense",
	"code": "167",
	"severity": 8,
	"message": "argument of type \"mpz_t *\" is incompatible with parameter of type \"__mpz_struct *\"",
	"source": "C/C++",
	"startLineNumber": 226,
	"startColumn": 22,
	"endLineNumber": 226,
	"endColumn": 22
},{
	"resource": "/home/biruk/Documents/eth/arb+tbot/uniswap.h",
	"owner": "cpptools",
	"severity": 8,
	"message": "cannot convert ‘__mpz_struct (*)[1]’ to ‘__mpz_struct*’",
	"source": "gcc",
	"startLineNumber": 226,
	"startColumn": 36,
	"endLineNumber": 226,
	"endColumn": 36
},{
	"resource": "/home/biruk/Documents/eth/arb+tbot/uniswap.h",
	"owner": "C/C++: IntelliSense",
	"code": "167",
	"severity": 8,
	"message": "argument of type \"mpz_t *\" is incompatible with parameter of type \"__mpz_struct *\"",
	"source": "C/C++",
	"startLineNumber": 227,
	"startColumn": 22,
	"endLineNumber": 227,
	"endColumn": 22
},{
	"resource": "/home/biruk/Documents/eth/arb+tbot/uniswap.h",
	"owner": "cpptools",
	"severity": 8,
	"message": "cannot convert ‘__mpz_struct (*)[1]’ to ‘__mpz_struct*’",
	"source": "gcc",
	"startLineNumber": 227,
	"startColumn": 36,
	"endLineNumber": 227,
	"endColumn": 36
}]

**Comment by mhw0** [comment]
No, `mpz_t` is a pointer itself. Just do: `eth_abi_mpint(&abi, r1);`

**Comment by DerXanRam** [comment]
it throws runtim error 

```
/usr/bin/ld: /tmp/ccBXKWZ4.o: undefined reference to symbol '__gmpz_init'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgmp.so.10: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

**Comment by mhw0** [comment]
Try adding `-lgmp` to `args` in `tasks.json`

**Comment by DerXanRam** [comment]
it runned succsussfuly and using `printf` it gives false decode result and using `gmp_printf` correct result.

using printf
```
decoded address: -10256
decoded address: -10240
decoded address: 1690645691
```
using gmp_printf
```
6729450845017214267
6729450845017214267 
decoded address: 1690645691
```

**Comment by mhw0** [comment]
Yes, becuase `printf` doesn't know about the `mpz_t`. To print in hex format, do `gmp_printf("%Zx\n", r1)`

**Comment by DerXanRam** [comment]
also i have a question. Can we encode uint256 data types using this new raw data type.... because if i want to send this data back to the RPC function i need a container that holds all of the digits.

**Comment by DerXanRam** [comment]
> Yes, becuase `printf` doesn't know about the `mpz_t`. To print in hex format, do `gmp_printf("%Zx\n", r1)`

so how to store the data to char* from this data type?

**Comment by mhw0** [comment]
> also i have a question. Can we encode uint256 data types using this new raw data type.... because if i want to send this data back to the RPC function i need a container that holds all of the digits.

Easy:
```c
struct eth_abi abi;
mpz_t mpz;
// 0xfff or 123 or load from uint64 etc..
mpz_init_set_str(mpz, "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", 0);

eth_abi_init(&abi, ETH_ABI_ENCODE);
eth_abi_mpint(&abi, mpz);
// ...
```

Here's the gmp manual:
https://gmplib.org/manual/

**Comment by DerXanRam** [comment]
> > also i have a question. Can we encode uint256 data types using this new raw data type.... because if i want to send this data back to the RPC function i need a container that holds all of the digits.
> 
> Easy:
> 
> ```c
> struct eth_abi abi;
> mpz_t mpz;
> // 0xfff or 123 or load from uint64 etc..
> mpz_init_set_str(mpz, "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", 0);
> 
> eth_abi_init(&abi, ETH_ABI_ENCODE);
> eth_abi_mpint(&abi, mpz);
> // ...
> ```
> 
> Here's the gmp manual: https://gmplib.org/manual/

ok thanks bro :pray:

**Comment by DerXanRam** [comment]
> > Yes, becuase `printf` doesn't know about the `mpz_t`. To print in hex format, do `gmp_printf("%Zx\n", r1)`
> 
> so how to store the data to char* from this data type?

i was trying.... i try to dereference and see it. but i lost...... i think i need some hand pls :pray:

**Comment by mhw0** [comment]
Closing the issue. Added in efd7ee074d40e57f6e7ef9a5b0e5fb1abf0cb638
