### ISSUE TITLE
Bytes decoder returns additional unexpected chars

### ISSUE THREAD

**Issue by DerXanRam** [mhw0/libethc#16]
Hello brother. i'm trying to decode string data type ABI response using this code
```
char *data ="0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000045553444300000000000000000000000000000000000000000000000000000000";

		// decoding
		struct eth_abi abi1;
		uint8_t *add;
		eth_abi_from_hex(&abi1, data, -1);
		eth_abi_bytes(&abi1, &add, NULL);
		eth_abi_free(&abi1);
		cout<<add<<endl;
```

and the out put is `USDCPU` . the supposed out put is `USDC`(u can check using this [ABI decoder](https://www.moesif.com/solidity-abi-hex-decoder/decode) ).The function i called is 

`function name() external pure returns (string memory);`

sometimes the decoder works fine and sometimes not. Here is when the decoder works fine

The data
`0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000650415245544f0000000000000000000000000000000000000000000000000000`

Decoded result `PARETO`
supposed result `PARETO`

**Comment by DerXanRam** [comment]
sorry for my late reply....let me test it

**Comment by DerXanRam** [comment]
> Hey. I think that's because the output is bytes not string (string is NULL-terminated). So, what you can do is to get the length of the bytes (`eth_abi_bytes(&abi, &add, &addlen)`) and print it like this:
> 
> ```c
> printf("add: %.*s\n", addled, add);
> ```

It worked if i pass length.  So if i want to use with variable length, do i must pass the character that have '\0' at the end?

**Comment by mhw0** [comment]
> It worked when i pass length. So if i want to use with variable length, do i must pass the character that have '\0' at the end?

If you mean `eth_abi_bytes` on encode, you need to count the characters in the string first (`strlen`?) and then pass it as the third argument  (`len`) because this function is supposed to work only with raw bytes, not with strings.

So, yes, we actually need a separate function for this case (`eth_abi_string`?)

**Comment by mhw0** [comment]
Issue: #17

**Comment by DerXanRam** [comment]
> > It worked when i pass length. So if i want to use with variable length, do i must pass the character that have '\0' at the end?
> 
> If you mean `eth_abi_bytes` on encode, you need to count the characters in the string first (`strlen`?) and then pass it as the third argument (`len`) because this function is supposed to work only with raw bytes, not with strings.
> 
> So, yes, we actually need a separate function for this case (`eth_abi_string`?)

yea on encode we can get from strlen(). but for decode impossible to predict output length. :+1:

**Comment by mhw0** [comment]
> yea on encode we can get from strlen(). but for decode impossible to predict output length. 👍

`bytes` and `len` are I/O parameters. So, it reads the bytes and the length as well on decode:
```c
eth_abi_bytes(&abi, &bytes, &len);
printf("output length: %zu\n", len);
```

**Comment by DerXanRam** [comment]
> > yea on encode we can get from strlen(). but for decode impossible to predict output length. 👍
> 
> `bytes` and `len` are I/O parameters. So, it reads the bytes and the length as well on decode:
> 
> ```c
> eth_abi_bytes(&abi, &bytes, &len);
> printf("output length: %zu\n", len);
> 
> // now you have a buffer with known length
> ```

tnx a lot....it returns exact size...... :pray:  .... and sorry for my late reply it is due to power failure
