### ISSUE TITLE
ci: run unit tests on every branch

### ISSUE THREAD

**Issue by mhw0** [mhw0/libethc#18]

**Comment by DerXanRam** [comment]
i'm on it bro :+1:

**Comment by mhw0** [comment]
I think it's in this file: `.github/workflows/ci-unix.yaml`

**Comment by DerXanRam** [comment]
> I think it's in this file: `.github/workflows/ci-unix.yaml`

i thought u say running unit test on `dev` branch cause u added `uint` data type for `rpl` and i was testing it. Can u tell me briefly what type of test u want to say? i think i missed your point.

**Comment by DerXanRam** [comment]
ok... so i must wait until it u merge it?

**Comment by mhw0** [comment]
> ok... so i must wait until it u merge it?

Fixed it. Closing the issue.

**Comment by DerXanRam** [comment]
> > ok... so i must wait until it u merge it?
> 
> Fixed it in a9e34baeb3800134ab32967e4b58255b8c082e81. Closing the issue.

Now i can test . Right?

**Comment by mhw0** [comment]
> Now i can test . Right?

test what? new functionality?

**Comment by DerXanRam** [comment]
> > Now i can test . Right?
> 
> test what? new functionality? 

`uint` in rpl

**Comment by DerXanRam** [comment]
> > > Now i can test . Right?
> > 
> > test what? new functionality? 
> 
> `uint` in rpl

I saw u deployed it in dev

**Comment by mhw0** [comment]
> I saw u deployed it in dev

Yes, you can use it.

**Comment by DerXanRam** [comment]
> > I saw u deployed it in dev
> 
> Yes, you can use it.

Ok tnx👍

**Comment by DerXanRam** [comment]
`uint` worked without a problem :+1:  ... tnx for this amazing library :pray:
