### ISSUE TITLE
deps: make `secp256k1` submodule

### ISSUE THREAD

**Issue by mhw0** [mhw0/libethc#19]

**Comment by DerXanRam** [comment]
u mean building [this lib](https://github.com/bitcoin-core/secp256k1) from scratch to decrease dependency??

**Comment by mhw0** [comment]
> u mean building [this lib](https://github.com/bitcoin-core/secp256k1) from scratch to decrease dependency??

No, I meant making it like this:
![Screenshot 2023-08-25 at 14 54 56](https://github.com/mhw0/libethc/assets/69183283/54d344ce-9751-4fc7-9425-52c4dc93ee86)

**Comment by DerXanRam** [comment]
> > u mean building [this lib](https://github.com/bitcoin-core/secp256k1) from scratch to decrease dependency??
> 
> No, I meant making it like this: ![Screenshot 2023-08-25 at 14 54 56](https://user-images.githubusercontent.com/69183283/263236466-54d344ce-9751-4fc7-9425-52c4dc93ee86.png)

It is not clear form me. If u have time, can u give me briefer description please :pray: . I don't want to nag u, ask u gazillion questions because  i'm curious to learn about this defi environment, the cryptography algorithms, how transaction works and so on.

**Comment by mhw0** [comment]
[Submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) is just a git feature. Without submodules you would have to install the dependencies manually. If you make all the dependencies submodules, you just clone the repository and `make && make install` and it will do everything for you.

**Comment by DerXanRam** [comment]
> [Submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) is just a git feature. Without submodules you would have to install the dependencies manually. If you make all the dependencies submodules, you just clone the repository and `make && make install` and it will do everything for you.
that's nice feature :+1:  .... now it is crystal clear.....Tnx a lot

**Comment by mhw0** [comment]
Okay, secp256k1 already comes with cmake and really easy to install. I don't think we need this. Closing the issue.
