### ISSUE TITLE
How should I compile on Windows?

### ISSUE THREAD

**Issue by ykky0** [mhw0/libethc#21]
How should I compile on Windows?

**Comment by mhw0** [comment]
Hello @ykky0. I'm not a windows user and couldn't get this working on windows using visual studio. If you have environments like `cygwin`, you can follow [these installation steps](https://mhw0.github.io/libethc/installation.html) and it should just work

There's actually an issue for this: #1.

PRs are welcome :)

**Comment by mhw0** [comment]
Closing the issue. Please follow this: #1
