### ISSUE TITLE
ABI parameters decoding for arrays data types are not working properly

### ISSUE THREAD

**Issue by DerXanRam** [mhw0/libethc#32]
Hello bro. I was working arround decoding data in the transaction to parameters([see this discussion](https://github.com/mhw0/libethc/discussions/10#discussioncomment-7176406)) ... the decoding process works when parameters are not array. but when they are array `eth_abi_array(&abi,&arrlen);` is not returning correct array size .. take a look the data, code and the  output

data
`0xd06ca61f00000000000000000000000000000000000000000000000000000000000027100000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000200000000000000000000000055d398326f99059ff775485246999027b319795500000000000000000000000055d398326f99059ff775485246999027b3197955`

code

```
void abiDecoder(string data)
	{
		char *input = strdup(data.c_str());
        char *fn="quote(uint256,address[])";
		mpz_t num;
		mpz_init(num);
		uint64_t arrlen;

		// decoding
		struct eth_abi abi;

		eth_abi_from_hex(&abi,input,data.length());
		eth_abi_call(&abi, &fn, NULL);
		eth_abi_mpint(&abi,num);
		eth_abi_array(&abi,&arrlen);
		char *add[arrlen];
		for(uint64_t i=0;i<arrlen;i++)
		    eth_abi_address(&abi,&add[i]);
		eth_abi_array_end(&abi);
 		eth_abi_call_end(&abi);
		ok(eth_abi_free(&abi));
        cout<<"arr len is "<<arrlen<<endl;
		//char *final = (char *)bytes;
		cout << "decoded " <<add[0] << endl;
	}
```

output

```
arr len is 0
decoded �[UUU
```

and if i set the array size manually, decoded result misses offset and results incorrect  form. This is the output when i set the array size to 2 manually

```
arr len is 2
decoded 0000000055d398326f99059ff775485246999027
```
The problem is not only in `address` array, it also exists in other data types.

The data is encoded correctly and u can check it[ using this website](https://calldata-decoder.apoorv.xyz/) and [using this uniswapv2 abi contract](https://etherscan.io/address/0x7a250d5630b4cf539739df2c5dacb4c659f2488d#code)

the function is 
``quote(uint256,address[])``

and the value inside the data are
```
uint256=10000
address[]=[0x55d398326f99059ff775485246999027b3197955,0x55d398326f99059ff775485246999027b3197955]
```

**Comment by mhw0** [comment]
Okay. Please, give me some time to investigate it.

**Comment by DerXanRam** [comment]
ok bro thanks a lot. u don't know how much u helped me on my project :pray:

**Comment by DerXanRam** [comment]
anything new?

**Comment by mhw0** [comment]
I’m so sorry, can’t find free time.

**Comment by DerXanRam** [comment]
> I’m so sorry, can’t find free time. 

Please notify me when u have time🙏...tnx

**Comment by DerXanRam** [comment]
Any update bro 👀

**Comment by mhw0** [comment]
I'm here! Found the issue. Fixing it...

**Comment by DerXanRam** [comment]
> I'm here! Found the issue. Fixing it...

🙏🙏🙏🙏

**Comment by mhw0** [comment]
a83c1c3 should fix this. Could you please test it?

**Comment by DerXanRam** [comment]
> a83c1c3 should fix this. Could you please test it?

Ok wait👍

**Comment by DerXanRam** [comment]
> [a83c1c3](https://github.com/mhw0/libethc/commit/a83c1c3286c4b16a7d2bf16900befb3651fb195a) should fix this. Could you please test it?

I tested with address and it's working in every possibility... i will try for all data types and notify u.. thanks very much bro :pray:

**Comment by DerXanRam** [comment]
for array, it worked, but for non array it's messed up... take a look
Inputs
```
addres=0xae4faf5d9189274750d850a6b69f36009249f873
uint256=1000000000000000000;
uint256=1000000000000000000;
uint256=10000000000000000000;
address=0xdb2a9d544e9808fb149da7cfdb43905c823f41eb;
uint256=1696752587
```

function
`addLiquidityETH(address token, uint256 amountTokenDesired, uint256 amountTokenMin, uint256 amountETHMin, address to, uint256 deadline)`

the code 
```
void abiDecoder(string data)
	{
		char *input = strdup(data.c_str());
        char *fn="addLiquidityETH(address,uint256,uint256,uint256,address,uint256)";
		mpz_t num0,num1,num2,num3;
		mpz_init(num0);
		mpz_init(num1);
		mpz_init(num2);
		mpz_init(num3);
		uint64_t arrlen=0;
        char *add0,*add1;
		// decoding
		struct eth_abi abi;
		eth_abi_from_hex(&abi,input,data.length());
		eth_abi_call(&abi, &fn, NULL);
		eth_abi_address(&abi,&add0);
		eth_abi_mpint(&abi,num0);
		eth_abi_mpint(&abi,num1);
		eth_abi_mpint(&abi,num2);
		eth_abi_address(&abi,&add1);
		eth_abi_mpint(&abi,num3);
 		eth_abi_call_end(&abi);
		ok(eth_abi_free(&abi));
        
		//char *final = (char *)bytes;
		cout << "address " <<add0 << endl;
		gmp_printf("%s %Zd\n","num 1", num0);
		gmp_printf("%s %Zd\n","num 2", num1);
		gmp_printf("%s %Zd\n","num 3", num2);
		cout << "address " <<add1 << endl;
		gmp_printf("%s %Zd\n","num 4", num3);
	}
```

output of the code

**Comment by DerXanRam** [comment]
and for some array entries... take a look

Inputs
```
uint256=5000000000000000000000
uint256=4784379002563414000000
address[]=[ "0x1bbf25e71ec48b84d773809b4ba55b6f4be946fb","0x0fc6c0465c9739d4a42daca22eb3b2cb0eb9937a" ]
address=0x986e078eed11bf6fbb1ee5bb9f1be787711f150b
uint256=1696753998
```
function
`swapExactTokensForTokens(uint256 amountIn, uint256 amountOutMin, address[] path, address to, uint256 deadline)`


code
```
void abiDecoder(string data)
	{
		char *input = strdup(data.c_str());
        char *fn="swapExactTokensForTokens(uint256,uint256,address[],address,uint256)";
		mpz_t num0,num1,num2,num3;
		mpz_init(num0);
		mpz_init(num1);
		mpz_init(num2);
		uint64_t arrlen=0;
        char *add1;
		// decoding
		struct eth_abi abi;
		eth_abi_from_hex(&abi,input,data.length());
		eth_abi_call(&abi, &fn, NULL);
		eth_abi_mpint(&abi,num0);
		eth_abi_mpint(&abi,num1);
		eth_abi_array(&abi,&arrlen);

		char *add[arrlen];
		for(int i=0;i<arrlen;i++)
		   eth_abi_address(&abi,&add[i]);

		eth_abi_array_end(&abi);
		eth_abi_address(&abi,&add1);
		eth_abi_mpint(&abi,num2);
 		eth_abi_call_end(&abi);
		ok(eth_abi_free(&abi));
        
		//char *final = (char *)bytes;
		gmp_printf("%s %Zd\n","num 1", num0);
		gmp_printf("%s %Zd\n","num 2", num1);
		for(int i=0;i<arrlen;i++)
		  cout<<"address "<<i+1<<" "<<add[i];
		cout << "address " <<add1 << endl;
		gmp_printf("%s %Zd\n","num 4", num2);
	}
```
output

runtime error inside abi.c line 181 "segmentation fault"

**Comment by DerXanRam** [comment]
also another senario
data
`0xb6f9de95000000000000000000000000000000000000000000000363c1d5de314a4e69dd0000000000000000000000000000000000000000000000000000000000000080000000000000000000000000e20ca5f4beda34d700aece837e2dd86ad858121b00000000000000000000000000000000000000000000000000000000652264fe0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2000000000000000000000000f043809056ac2492c4aae6317705f751082c0db1`

input
```
uint256=16007294426028822129117
addtess[]=["0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2", "0xf043809056ac2492c4aae6317705f751082c0db1" ]
address=0xe20ca5f4beda34d700aece837e2dd86ad858121b
uint256=1696752894
```

function
`swapExactETHForTokensSupportingFeeOnTransferTokens(uint256 amountOutMin, address[] path, address to, uint256 deadline)`
code
```
void abiDecoder(string data)
	{
		char *input = strdup(data.c_str());
        char *fn="swapExactETHForTokensSupportingFeeOnTransferTokens(uint256,address[],address,uint256)";
		mpz_t num0,num1,num2,num3;
		mpz_init(num0);
		mpz_init(num1);
		uint64_t arrlen=0;
        char *add1;
		// decoding
		struct eth_abi abi;
		eth_abi_from_hex(&abi,input,data.length());
		eth_abi_call(&abi, &fn, NULL);
		eth_abi_mpint(&abi,num0);
		eth_abi_array(&abi,&arrlen);

		char *add[arrlen];
		for(int i=0;i<arrlen;i++)
		   eth_abi_address(&abi,&add[i]);

		eth_abi_array_end(&abi);
		eth_abi_address(&abi,&add1);
		eth_abi_mpint(&abi,num1);
 		eth_abi_call_end(&abi);
		ok(eth_abi_free(&abi));
        
		//char *final = (char *)bytes;
		gmp_printf("%s %Zd\n","num 1", num0);
		for(int i=0;i<arrlen;i++)
		  cout<<"address "<<i+1<<" "<<add[i];
		cout << "address " <<add1 << endl;
		gmp_printf("%s %Zd\n","num 4", num1);
	}

```
output
num 1 16007294426028822129117
address 1= c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2
address 2= c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2address 
address=e20ca5f4beda34d700aece837e2dd86ad858121b
num 4 1290513979958332680737930990062599183846224695835

**Comment by DerXanRam** [comment]
the problem of not correctly reading array size is also exist in` uint256,bool`  (uint256 as mpint) array data types

for `uint8,uint16,uint32,uint64` it reads array size but not correct. for example inside my test data there are 2 array elements but it returns 1 array size

**Comment by DerXanRam** [comment]
bro :eyes:

**Comment by mhw0** [comment]
Yes, I see the problem. But, sorry, I'm just busy right now. Maybe you want to fix this?

**Comment by DerXanRam** [comment]
OK bro. Just notify me when u have time. I  will try.....And sorry if i nagging u :pray: 

Thanks

**Comment by DerXanRam** [comment]
Good morning bro. Anything new? 👀

**Comment by mhw0** [comment]
I'm so sorry @DerXanRam You have the whole codebase and I would appreciate if you fixed it and opened a PR. Thank you!

**Comment by DerXanRam** [comment]
> I'm so sorry @DerXanRam You have the whole codebase and I would appreciate if you fixed it and opened a PR. Thank you!

I returned this morning because i tried for the last 3 days to work on your code and I completely lost due to

1. U are programmer and u know how hard is to understand the code written by others especially for beginners.

2. I am even pretty new to c++ and the code is C.

3. Lot of variable names written in short manner and few comments in some major part of the code makes hard for me to follow the execution flow.

I know, i continuously nagged you and i apologize for that🙏 and my behaviour.

**Comment by mhw0** [comment]
No, you're good. Okay, I'll try to fix this today. Sorry for the delay.

**Comment by mhw0** [comment]
Hello @DerXanRam Can you please test this: e8ddbf418b9204b1953df4f418a31e1f2df65fb4

**Comment by mhw0** [comment]
it's in the dev branch

**Comment by DerXanRam** [comment]
Testing ......

**Comment by DerXanRam** [comment]
I tested the fix with the above test cases and it's working perfectly.

Also I'm testing encoding and decoding of uint256,address,uint256[],address[] to check it doesn't break other functionalities. More test reults will come in few hours :+1:  ..

**Comment by mhw0** [comment]
Sounds great. Closing the issue. Please reopen the issue if you find anything. Thanks!

**Comment by DerXanRam** [comment]
> the problem of not correctly reading array size is also exist in` uint256` and ` bool` (uint256 as mpint) array data types
> 
> for `uint8,uint16,uint32,uint64` it reads array size but not correct. for example inside my test data there are 2 array elements but it reads 1 array element only.

But this problem still exists when i decode a function that have input of `uint256[],address[],address,uint256`.  wait let me give u some code snippet

**Comment by DerXanRam** [comment]
I tested for `uint8,uint16,uint32,uint64,mpimt,bool and address` and their array types and noting is broken.
But there is a problem decoding ABI inputs of data type `bytes` and i can't say this surely because my exposer and usage of `byte8,bytes16,bytes32 and bytes` using this Library is very low. So it may be my coding... i will share the code snippet
