### ISSUE TITLE
leading zero bytes

### ISSUE THREAD

**Issue by DerXanRam** [mhw0/libethc#9]
Hello bro. how u doing...... after converting my real private key to bytes and sign a real transaction there are two problems. The first one is, as u mentioned in the previous issue, u suggest me to use [this website](https://abi.hashex.org/) to make ABI. But when i compare the result of ABI generated by the code and by the website, they differ slightly with the same input...see below

By the website
`0x7ff36ab500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000a9d0a7dc416f586491f2fb596731598f937617b50000000000000000000000000000000000000000000000000000000014aae8060000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2000000000000000000000000dac17f958d2ee523a2206206994597c13d831ec7`
By the code
`0xfda71c7f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000a9d0a7dc416f586491f2fb596731598f937617b50000000000000000000000000000000000000000000000000000000014aae8060000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2000000000000000000000000dac17f958d2ee523a2206206994597c13d831ec7`

See the first 10 digits ... they differ at that point, the rest is the same.
After this i generated raw transaction using the code below,my address(no balance), the address's real private key and the ABI generated by the website. the code is

```
char *SignTransaction()
{
	char *abi_result="0x7ff36ab500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000a9d0a7dc416f586491f2fb596731598f937617b50000000000000000000000000000000000000000000000000000000014aae8060000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2000000000000000000000000dac17f958d2ee523a2206206994597c13d831ec7";// = ABIFunction();

	struct eth_rlp rlp0, rlp1;
	struct eth_ecdsa_signature sign;
	  
	uint8_t privkey[] ={0x80, 0x3e, 0x53, 0x83, 0x51, 0x93, 0xdd, 0x6e, 
	                    0xad, 0x61, 0xa2, 0x5a, 0x74, 0x5f, 0xa6, 0x35, 
						0x86, 0xb4, 0xb2, 0xdd, 0x7b, 0x6a, 0xbe, 0x4a, 
						0x06, 0xfa, 0x7f, 0x33, 0xc1, 0x1a, 0xed, 0x81}; //real private key of the account 0xa9d0a7dC416f586491f2fb596731598F937617b5
	//ok(eth_hex_to_bytes(&privkey,keys,64));
	
	uint8_t nonce = 0x00, zero = 0x00, keccak[32], *rlp0bytes, *r, *s;
	char *gasprice = "0x04a817c800", *gaslimit = "0x5208", *value = "0x00";
	char *toaddr = "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D", *txn;
	uint16_t chainid = 0x1, v;
	size_t rlp0len, rlp1len, siglen = 32;

	ok(eth_rlp_init(&rlp0, ETH_RLP_ENCODE));
	ok(eth_rlp_array(&rlp0));
	ok(eth_rlp_uint8(&rlp0, &nonce));
	ok(eth_rlp_hex(&rlp0, &gasprice, NULL));
	ok(eth_rlp_hex(&rlp0, &gaslimit, NULL));
	ok(eth_rlp_address(&rlp0, &toaddr));
	ok(eth_rlp_hex(&rlp0, &value, NULL));
	ok(eth_rlp_hex(&rlp0, &abi_result, NULL));
	ok(eth_rlp_uint16(&rlp0, &chainid));
	ok(eth_rlp_uint8(&rlp0, &zero)); //   0x,
	ok(eth_rlp_uint8(&rlp0, &zero)); //   0x,
	ok(eth_rlp_array_end(&rlp0));	 // ]

	ok(eth_rlp_to_bytes(&rlp0bytes, &rlp0len, &rlp0));
	ok(eth_rlp_free(&rlp0));

	// compute the keccak hash of the encoded rlp elements
	ok(eth_keccak256(keccak, rlp0bytes, rlp0len));
	free(rlp0bytes);

	// sign the transaction
	ok(eth_ecdsa_sign(&sign, privkey, keccak));

	// calculate v
	v = sign.recid + chainid * 2 + 35;
	r = sign.r;
	s = sign.s;

	ok(eth_rlp_init(&rlp1, ETH_RLP_ENCODE));
	ok(eth_rlp_array(&rlp1));
	ok(eth_rlp_uint8(&rlp1, &nonce));
	ok(eth_rlp_hex(&rlp1, &gasprice, NULL));
	ok(eth_rlp_hex(&rlp1, &gaslimit, NULL));
	ok(eth_rlp_address(&rlp1, &toaddr));
	ok(eth_rlp_hex(&rlp1, &value, NULL));
	ok(eth_rlp_hex(&rlp1, &abi_result, NULL)); // replaced
	ok(eth_rlp_uint16(&rlp1, &v));
	ok(eth_rlp_bytes(&rlp1, &r, &siglen));
	ok(eth_rlp_bytes(&rlp1, &s, &siglen));
	ok(eth_rlp_array_end(&rlp1));

	// FIX3: this actually returns the output length
	ok(eth_rlp_to_hex(&txn, &rlp1) > 0);
	ok(eth_rlp_free(&rlp1));
	return txn;
}
```
and the RPC response is 
```
{
    "error": "rlp: non-canonical integer (leading zero bytes) for *big.Int, decoding into (*types.Transaction)(types.LegacyTx).V"
}
```
which seems formatting issue. i try to look on the internet about the problem and i found this [forum answer](https://ethereum.stackexchange.com/questions/71616/ethereum-boardcast-shows-error-non-canonical-integer-leading-zero-bytes-for). They say this happens because `S` have leading zero byte. I try to work around in the libethc, But I couldn't fix it.  Can u check it please?

**Comment by mhw0** [comment]
Hi @DerXanRam.

> See the first 10 digits ... they differ at that point, the rest is the same.

The first four bytes represent the function selector. Can you please show me your ABI encode code?

> which seems formatting issue. i try to look on the internet about the problem and i found this [forum answer](https://ethereum.stackexchange.com/questions/71616/ethereum-boardcast-shows-error-non-canonical-integer-leading-zero-bytes-for). They say this happens because S have leading zero byte

I think these lines are causing the error, because, both `r` and `s` values don't start with `0`:
```c
ok(eth_rlp_hex(&rlp0, &value, NULL));
// and second one
ok(eth_rlp_hex(&rlp1, &value, NULL));
```
try these instead:
```c
ok(eth_rlp_uint8(&rlp0, &zero));
// and second one
ok(eth_rlp_uint8(&rlp1, &zero));
```

**Comment by mhw0** [comment]
Or, can you check if your actual `r` and `s` values have leading zeros?

**Comment by DerXanRam** [comment]
> The first four bytes represent the function selector. Can you please show me your ABI encode code?
Here is the ABI code
```
char *ABIFunction()
{
	struct eth_abi abi;
	char *fn = "swapExactETHForTokens(uint,address[],address,uint)", *hex;
	char *weth = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2";
	char *usdt = "0xdAC17F958D2ee523a2206206994597C13D831ec7";
	char *to_address = "0xa9d0a7dC416f586491f2fb596731598F937617b5";

	uint64_t path_len = 2;
	size_t hexlen;
	uint64_t amount_out_min = 0, deadline = 346744838;
	//////////////////
	eth_abi_init(&abi, ETH_ABI_ENCODE);
	eth_abi_call(&abi, &fn, NULL);
	eth_abi_uint64(&abi, &amount_out_min);
	eth_abi_array(&abi, &path_len); // open an array
	eth_abi_address(&abi, &weth);
	eth_abi_address(&abi, &usdt);
	eth_abi_array_end(&abi); // close the array
	eth_abi_address(&abi, &to_address);
	eth_abi_uint64(&abi, &deadline);
	eth_abi_call_end(&abi);

	ok(eth_abi_to_hex(&abi, &hex, &hexlen));
	ok(eth_abi_free(&abi));
	return hex;
}
```

> try these instead:
> 
> ```c
> ok(eth_rlp_uint8(&rlp0, &zero));
> // and second one
> ok(eth_rlp_uint8(&rlp1, &zero));
> ```

Ok bro.... testing

**Comment by DerXanRam** [comment]
> Or, can you check if your actual `r` and `s` values have leading zeros?

Yea i think s have leading zero  when i check on [online decoder](https://www.ethereumdecoder.com/?search=0xf9014b808504a817c800825208947a250d5630b4cf539739df2c5dacb4c659f2488d80b8e47ff36ab500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000a9d0a7dc416f586491f2fb596731598f937617b50000000000000000000000000000000000000000000000000000000014aae8060000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2000000000000000000000000dac17f958d2ee523a2206206994597c13d831ec7820025a00adaf08507a56902b778f93755bb969c65ab0841f2117aaea768c03d1ecf640ea031b675c1d7e61b8768c44675d33d1a9f6d5970d2ca2ae4ebeecf3529c2b38188) .... here is the result

"r": "0x0adaf08507a56902b778f93755bb969c65ab0841f2117aaea768c03d1ecf640e"

**Comment by mhw0** [comment]
> Yea i think r have leading zero when i check on [online decoder](https://www.ethereumdecoder.com/?search=0xf9014b808504a817c800825208947a250d5630b4cf539739df2c5dacb4c659f2488d80b8e47ff36ab500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000a9d0a7dc416f586491f2fb596731598f937617b50000000000000000000000000000000000000000000000000000000014aae8060000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2000000000000000000000000dac17f958d2ee523a2206206994597c13d831ec7820025a00adaf08507a56902b778f93755bb969c65ab0841f2117aaea768c03d1ecf640ea031b675c1d7e61b8768c44675d33d1a9f6d5970d2ca2ae4ebeecf3529c2b38188) ....also [another decoder](https://toolkit.abdk.consulting/ethereum#transaction) ...here is the result
"r": "0x0adaf08507a56902b778f93755bb969c65ab0841f2117aaea768c03d1ecf640e"

No, that's a hex value. First two digits should be zero to cause the error.

**Comment by mhw0** [comment]
> Here is the ABI code

Okay, [this](https://solidity-by-example.org/function-selector/) resource says that `transfer(address,uint256)` should be `a9059cbb`, and the code is producing the same result. So, it's working as intended I think.

**Comment by DerXanRam** [comment]
> > Here is the ABI code
> 
> Okay, [this](https://solidity-by-example.org/function-selector/) resource says that `transfer(address,uint256)` should be `a9059cbb`, and the code is producing the same result. So, it's working as intended I think.

from the decoder i mentioned above, `From address` is my address right? But is showing different found inside the code? or do i miss something?

**Comment by DerXanRam** [comment]
> I think these lines are causing the error, because, both `r` and `s` values don't start with `0`:
> 
> ```c
> ok(eth_rlp_hex(&rlp0, &value, NULL));
> // and second one
> ok(eth_rlp_hex(&rlp1, &value, NULL));
> ```
> 
> try these instead:
> 
> ```c
> ok(eth_rlp_uint8(&rlp0, &zero));
> // and second one
> ok(eth_rlp_uint8(&rlp1, &zero));
> ```

and after i add this leading zero gone and another error realm appeares :smiling_face_with_tear:  called
```
{
    "error": "Couldn't decode hex: 0XF9014B808504A817C800825208947A250D5630B4CF539739DF2C5DACB4C659F2488D80B8E47FF36AB500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000A9D0A7DC416F586491F2FB596731598F937617B50000000000000000000000000000000000000000000000000000000014AAE8060000000000000000000000000000000000000000000000000000000000000002000000000000000000000000C02AAA39B223FE8D0A0E5C4F27EAD9083C756CC2000000000000000000000000DAC17F958D2EE523A2206206994597C13D831EC7820025A00ADAF08507A56902B778F93755BB969C65AB0841F2117AAEA768C03D1ECF640EA031B675C1D7E61B8768C44675D33D1A9F6D5970D2CA2AE4EBEECF3529C2B38188"
}
```

**Comment by mhw0** [comment]
> from the decoder i mentioned above, From address is my address right? But it is showing different address from the address found inside the code? or do i miss something?

You don't replace anything. If your function signature is `transfer(address,uint256)`, it should be passed to `eth_abi_call` as is. But, when you encode the arguments, they must match the signature. For example, this is wrong:

```c
char *sig = "transfer(address, uint256,uint256)";
eth_abi_call(&abi, &sig, NULL);
  eth_abi_address(&abi, &myaddr);
  eth_abi_bool(&abi, &b); // type mismatch
  // we did not pass the third argument at all
eth_abi_call_end(&abi);
```

**Comment by mhw0** [comment]
> and after i add this correction, leading zero error gone and another error realm appeares 🥲 called

The transaction is correct, maybe it starts with `0x`, not `0X`?

**Comment by DerXanRam** [comment]
This is the whole code....

```
char *ABIFunction()
{
	struct eth_abi abi;
	char *fn = "swapExactETHForTokens(uint,address[],address,uint)", *hex;
	char *weth = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2";
	char *usdt = "0xdAC17F958D2ee523a2206206994597C13D831ec7";
	char *to_address = "0xa9d0a7dC416f586491f2fb596731598F937617b5";

	uint64_t path_len = 2;
	size_t hexlen;
	uint64_t amount_out_min = 0, deadline = 346744838;
	//////////////////
	eth_abi_init(&abi, ETH_ABI_ENCODE);
	eth_abi_call(&abi, &fn, NULL);
	eth_abi_uint64(&abi, &amount_out_min);
	eth_abi_array(&abi, &path_len); // open an array
	eth_abi_address(&abi, &weth);
	eth_abi_address(&abi, &usdt);
	eth_abi_array_end(&abi); // close the array
	eth_abi_address(&abi, &to_address);
	eth_abi_uint64(&abi, &deadline);
	eth_abi_call_end(&abi);

	ok(eth_abi_to_hex(&abi, &hex, &hexlen));
	ok(eth_abi_free(&abi));
	return hex;
}
char *SignTransaction()
{
	char *abi_result="0x7ff36ab500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000a9d0a7dc416f586491f2fb596731598f937617b50000000000000000000000000000000000000000000000000000000014aae8060000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2000000000000000000000000dac17f958d2ee523a2206206994597c13d831ec7";// = ABIFunction();

	struct eth_rlp rlp0, rlp1;
	struct eth_ecdsa_signature sign;
	  
	uint8_t privkey[] ={0x80, 0x3e, 0x53, 0x83, 0x51, 0x93, 0xdd, 0x6e, 
	                    0xad, 0x61, 0xa2, 0x5a, 0x74, 0x5f, 0xa6, 0x35, 
						0x86, 0xb4, 0xb2, 0xdd, 0x7b, 0x6a, 0xbe, 0x4a, 
						0x06, 0xfa, 0x7f, 0x33, 0xc1, 0x1a, 0xed, 0x81}; //real private key of the account 0xa9d0a7dC416f586491f2fb596731598F937617b5
	//ok(eth_hex_to_bytes(&privkey,keys,64));
	
	uint8_t nonce = 0x00, zero = 0x00, keccak[32], *rlp0bytes, *r, *s;
	char *gasprice = "0x04a817c800", *gaslimit = "0x5208", *value = "0x00";
	char *toaddr = "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D", *txn;
	uint16_t chainid = 0x1, v;
	size_t rlp0len, rlp1len, siglen = 32;

	ok(eth_rlp_init(&rlp0, ETH_RLP_ENCODE));
	ok(eth_rlp_array(&rlp0));
	ok(eth_rlp_uint8(&rlp0, &nonce));
	ok(eth_rlp_hex(&rlp0, &gasprice, NULL));
	ok(eth_rlp_hex(&rlp0, &gaslimit, NULL));
	ok(eth_rlp_address(&rlp0, &toaddr));
	ok(eth_rlp_uint8(&rlp0, &zero));
	ok(eth_rlp_hex(&rlp0, &abi_result, NULL));
	ok(eth_rlp_uint16(&rlp0, &chainid));
	ok(eth_rlp_uint8(&rlp0, &zero)); //   0x,
	ok(eth_rlp_uint8(&rlp0, &zero)); //   0x,
	ok(eth_rlp_array_end(&rlp0));	 // ]

	ok(eth_rlp_to_bytes(&rlp0bytes, &rlp0len, &rlp0));
	ok(eth_rlp_free(&rlp0));

	// compute the keccak hash of the encoded rlp elements
	ok(eth_keccak256(keccak, rlp0bytes, rlp0len));
	free(rlp0bytes);

	// sign the transaction
	ok(eth_ecdsa_sign(&sign, privkey, keccak));

	// calculate v
	v = sign.recid + chainid * 2 + 35;
	r = sign.r;
	s = sign.s;

	ok(eth_rlp_init(&rlp1, ETH_RLP_ENCODE));
	ok(eth_rlp_array(&rlp1));
	ok(eth_rlp_uint8(&rlp1, &nonce));
	ok(eth_rlp_hex(&rlp1, &gasprice, NULL));
	ok(eth_rlp_hex(&rlp1, &gaslimit, NULL));
	ok(eth_rlp_address(&rlp1, &toaddr));     
    ok(eth_rlp_uint8(&rlp1, &zero));
	ok(eth_rlp_hex(&rlp1, &abi_result, NULL)); // replaced
	ok(eth_rlp_uint16(&rlp1, &v));
	ok(eth_rlp_bytes(&rlp1, &r, &siglen));
	ok(eth_rlp_bytes(&rlp1, &s, &siglen));
	ok(eth_rlp_array_end(&rlp1));

	// FIX3: this actually returns the output length
	ok(eth_rlp_to_hex(&txn, &rlp1) > 0);
	ok(eth_rlp_free(&rlp1));
	return txn;
}
```

This is how i call the rpc on my terminal using this [doc guide ](https://docs.blastapi.io/blast-documentation/apis-documentation/ethereum/eth_sendrawtransaction)

```
curl https://eth-mainnet.blastapi.io/b871b6ef-cdc2-4c11-b791-9fcaf4da878d -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"eth_sendRawTransaction","params":["0xf9014b808504a817c800825208947a250d5630b4cf539739df2c5dacb4c659f2488d80b8e47ff36ab500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000a9d0a7dc416f586491f2fb596731598f937617b50000000000000000000000000000000000000000000000000000000014aae8060000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2000000000000000000000000dac17f958d2ee523a2206206994597c13d831ec7820025a00adaf08507a56902b778f93755bb969c65ab0841f2117aaea768c03d1ecf640ea031b675c1d7e61b8768c44675d33d1a9f6d5970d2ca2ae4ebeecf3529c2b38188"],"id":1}'
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"read V: rlp: non-canonical integer format"}}
biruk@bura:~$ curl https://eth-mainnet.blastapi.io/b871b6ef-cdc2-4c11-b791-9fcaf4da878d -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"eth_sendRawTransaction","params":["0xf9014b808504a817c800825208947a250d5630b4cf539739df2c5dacb4c659f2488d80b8e47ff36ab500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000a9d0a7dc416f586491f2fb596731598f937617b50000000000000000000000000000000000000000000000000000000014aae8060000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2000000000000000000000000dac17f958d2ee523a2206206994597c13d831ec7820025a00adaf08507a56902b778f93755bb969c65ab0841f2117aaea768c03d1ecf640ea031b675c1d7e61b8768c44675d33d1a9f6d5970d2ca2ae4ebeecf3529c2b38188"],"id":1}'
```
and this is the RPC response
```{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"read V: rlp: non-canonical integer format"}}```

**Comment by DerXanRam** [comment]
> > and after i add this correction, leading zero error gone and another error realm appeares 🥲 called
> 
> The transaction is correct, maybe it starts with `0x`, not `0X`?

I double check that... and because i use terminal it is easy to differernciate O or o and 0(zero) :+1: :

**Comment by DerXanRam** [comment]
and onother [online decoder ](https://live.blockcypher.com/eth/decodetx/), which the response is the same with the RPC i use in curl, throughs this response different response
```
{
    "error": "Couldn't decode hex: 0XF9014B808504A817C800825208947A250D5630B4CF539739DF2C5DACB4C659F2488D80B8E47FF36AB500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000A9D0A7DC416F586491F2FB596731598F937617B50000000000000000000000000000000000000000000000000000000014AAE8060000000000000000000000000000000000000000000000000000000000000002000000000000000000000000C02AAA39B223FE8D0A0E5C4F27EAD9083C756CC2000000000000000000000000DAC17F958D2EE523A2206206994597C13D831EC7820025A00ADAF08507A56902B778F93755BB969C65AB0841F2117AAEA768C03D1ECF640EA031B675C1D7E61B8768C44675D33D1A9F6D5970D2CA2AE4EBEECF3529C2B38188"
}
```

**Comment by mhw0** [comment]
Oh, I think, I know what the problem is. We're encoding `v` as `uint16`, and, `v` is less than 255. So, in bytes, it would be `00xx`. Just replace `ok(eth_rlp_uint16(&rlp1, &v));` with `ok(eth_rlp_uint8(&rlp1, &v));` and the type of `v` should be `uint8_t` in the code.

**Comment by DerXanRam** [comment]
> Oh, I think, I know what the problem is. We're encoding `v` as `uint16`, and, `v` is less than 255. So, in bytes, it would be `00xx`. Just replace `ok(eth_rlp_uint16(&rlp1, &v));` with `ok(eth_rlp_uint8(&rlp1, &v));` and the type of `v` should be `uint8_t` in the code.

Wow bro...finally :smiley:  ... I missed this response like for 4 days....

```{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"INTERNAL_ERROR: insufficient funds"}}```

Thanks...and by the way.... i am finishing the code part that sends the raw transaction to the RPC-API, receive the response and store in json format. It needs cleaning and some work to make handy to use. once i finished i will pull request here :pray: ...

**Comment by mhw0** [comment]
Please, be careful when using this library with real money. I don't guarantee anything. If you have any other questions, I've just opened a [discussion](https://github.com/mhw0/libethc/discussions/10). Have a great day!
